version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: hospital_postgres
    environment:
      POSTGRES_DB: hospital_management
      POSTGRES_USER: hospital_admin
      POSTGRES_PASSWORD: hospital_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_backup.sql:/docker-entrypoint-initdb.d/restore.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_admin -d hospital_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hospital_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hospital_admin:hospital_password@postgres:5432/hospital_management
      - JWT_SECRET=your-super-secret-jwt-key-minimum-32-characters-long
      - SESSION_SECRET=your-super-secret-session-key-minimum-32-characters-long
      - PORT=5000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: